source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'iOS' do

  platform :ios, '12.0'

  pod 'HLSpriteKit', :path => '../'

  target 'iOS-Tests' do
    inherit! :search_paths
  end

end

target 'macOS' do

  platform :osx, '10.11'

  pod 'HLSpriteKit', :path => '../'

  target 'macOS-Tests' do
    inherit! :search_paths
  end

end
